{% set name = "FormEncode" %}
{% set version = "2.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: eb74d223078a28cf015fa88966c6e34f2d18d75127318d65c144bed9afc4263f

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools_scm >=7
  run:
    - python >={{ python_min }}
    - setuptools

test:
  imports:
    - formencode
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check

about:
  home: http://formencode.org
  license: MIT
  license_file: LICENSE.txt
  summary: HTML form validation, generation, and conversion package
  dev_url: https://github.com/formencode/formencode

extra:
  recipe-maintainers:
    - windelbouwman
    - synapticarbors
