{% set name = "FormEncode" %}
{% set version = "2.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: eb74d223078a28cf015fa88966c6e34f2d18d75127318d65c144bed9afc4263f

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
    - setuptools_scm
    - setuptools_scm_git_archive
  run:
    - python >=3.6
    - setuptools
    - six

test:
  imports:
    - formencode

about:
  home: http://formencode.org
  license: MIT
  license_file: LICENSE.txt
  summary: HTML form validation, generation, and conversion package
  dev_url: https://github.com/formencode/formencode

extra:
  recipe-maintainers:
    - windelbouwman
    - synapticarbors
